### ISSUE TITLE
When I run the code in README , always failed: Connection timed out: connect. 

### ISSUE THREAD

**Issue by huage1994** [jenkinsci/java-client-api#224]
When I run the code in README as following pictuer, I can get job information, but can not get job details. It prompt me that Connect timed out.  And I visit the link in browser very easily.
I am new ,and I really wonder why.

![image](https://cloud.githubusercontent.com/assets/8039295/21802907/b0973d80-d762-11e6-9e71-28e23269d5b7.png)

**Comment by khmarbaise** [comment]
First why are you giving empty username/password strings? If you don't use username/password than just omit the parameters. Why are username/password followed by ":"? Are you using Groovy instead of Java? How is the error message "failed: Connection timed out: ..." produced? Please check first to get the information for a single job like: BTW: Which version of the java-api-client do you use? And which Jenkins version are you using?

```java
JenkinsServer js = new JenkinsServer ( URI.create("http:/....") );
JobWithDetails job = js.getJob("TheJobYouWouldLIkeToGetInformationAbout");
JobWithDetails details = job.details();
```

Furthermore the timed out error message can have several causes. If your Jenkins is handled behind an Apache Web-Server (proxied? or for authentication purposes?) etc. and of course network issues...

**Comment by huage1994** [comment]
1. username/password:  I' m sorry that I deleted them when I make a screenshot.
2. Groovy or java :  Java
3.version: 
            jenkins:    2.32.1
            java-api-client: 0.3.7
4.proxy:  I can visit jenkins server without proxy in browser.

I just think it's strange that I can get the job name as you can see in the attached picture but Connection timed out occurs when " JobWithDetails job = jobs.get("MCS-server-build-2-Canary-Dev").details();  "
![image](https://cloud.githubusercontent.com/assets/8039295/21832725/1c2a03f4-d7e8-11e6-83b7-f271d02c60e5.png)

Thanks a lot.

**Comment by khmarbaise** [comment]
So is the problem solved ? Based on the screen I see the timeout keeps there? A connection time out can have several causes...You should check if Jenkins is behind a Apache Proxy etc. ?

**Comment by huage1994** [comment]
umm, Not solved.  It is urgent , so I read your source and directlly call the http api of jenkins in my code. I'll check it again when free.
Thanks a lot .
